# Generated by Django 2.2.12 on 2022-04-28 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AorB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AorB', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=255)),
                ('photo', models.IntegerField()),
                ('weixin', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('booth_num', models.IntegerField()),
                ('B_leixin', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tiaozaoAorB',
            },
        ),
        migrations.CreateModel(
            name='Fenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibei', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fenlei',
            },
        ),
        migrations.CreateModel(
            name='Rootadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiaozao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('booth_num', models.IntegerField()),
                ('photo', models.IntegerField()),
                ('weixin', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=30)),
                ('cover_pic', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('shoptext', models.TextField(default='')),
            ],
            options={
                'db_table': 'tiaozao',
            },
        ),
    ]
