# Generated by Django 2.2.12 on 2022-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiaozao',
            name='booth_num',
            field=models.CharField(max_length=50),
        ),
    ]
