# Generated by Django 2.2.12 on 2022-04-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozaoapp', '0002_auto_20220429_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aorb',
            name='AorB',
            field=models.CharField(max_length=50),
        ),
    ]
